apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "lanchonete"
  POSTGRES_HOST: "postgresql-lanchonete"
  application.properties: |
    spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    spring.datasource.username=${POSTGRES_USER}
    spring.datasource.password=${POSTGRES_PASSWORD}