apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: kube-system
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
