apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-metrics
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
