version: '3.10'
services:


  db:
    container_name: postgresql-lanchonete
    image: postgres:12.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: pedido
    ports:
      - 5432:5432