spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  datasource:
    driver-class-name: org.h2.Driver
    username: postgres
    password: ${DATABASE_POSTGRES_PASSWORD:postgres}
    url: jdbc:h2:mem:lanchonete_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  h2:
    console:
      enabled: true
      path: /h2

