postgres:
  username: postgres
  password: ${DATABASE_POSTGRES_PASSWORD:postgres}
  schema: lanchonete
  url: localhost:5433

amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_order
  password: 123456