logging:
  level:
    root: info

postgres:
  username: postgres
  password: postgres
  schema: producao
  url: localhost:${postgres.port}

amqp:
  host: localhost
  port: 5672
  username: adm_production
  password: 123456

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration