spring:
  application:
    name: fiap-tech-challenge
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: false
    defer-datasource-initialization: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
  sql:
    init:
      mode: never
  elasticsearch:
    rest:
      uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://localhost:5432/lanchonete
    username: postgres
    password: postgres
  main:
    lazy-initialization: true

management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      show-details: always
    web:
      exposure:
        include: *
    prometheus:
      enabled: true
  server:
    port: 8080
    address: 127.0.0.1
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.fiap.tech: DEBUG
