apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "lanchonete"
  POSTGRES_HOST: "postgresql-lanchonete"