apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lanchonete-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lanchonete-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "32000"
    spec:
      containers:
        - name: lanchonete-app
          image: lanchonete-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: lanchonete-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"