apiVersion: v1
kind: Service
metadata:
  name: lanchonete-app
spec:
  type: NodePort
  selector:
    app: lanchonete-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000