apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: default
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io