@startuml
actor Cliente
participant Interface
participant Backend
participant SistemaDePagamento
participant Monitoramento

Cliente -> Interface: Selecionar itens
Interface -> Backend: Enviar detalhes do pedido
Backend -> Backend: Criar Pedido
Backend -> SistemaDePagamento: Gerar QR Code
SistemaDePagamento -> Interface: QR Code para pagamento
Cliente -> SistemaDePagamento: Pagamento via QR Code
SistemaDePagamento -> Backend: Confirmar pagamento
Backend -> Monitoramento: Atualizar status do pedido
Monitoramento -> Cliente: Notificar que o pedido está pronto

@enduml