name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Build Docker image
        run: docker build -t gabiponcet/lanchonete-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push gabiponcet/lanchonete-app:latest

      - name: Clone Kubernetes repo
        run: |
          git clone https://gabiponcet:${{ secrets.GITHUB_TOKEN }}@github.com/DenisWm/infra-k8s.git k8s-repo

      - name: Copy K8s files
        run: |
          cp -R k8s/* k8s-repo/

      - name: Update Kubernetes manifests
        run: |
          find k8s-repo -name 'deployment.yaml' -exec sed -i 's|image:.*|image: gabiponcet/lanchonete-app:latest|' {} +

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Install LocalStack
        run: pip install localstack

      - name: Start LocalStack
        run: localstack start -d

      - name: Initialize Terraform
        run: terraform init
        working-directory: k8s-repo/terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: k8s-repo/terraform

      - name: Commit and push changes to Kubernetes repo
        run: |
          cd k8s-repo
          git config --global user.email "gabiponcet@gmail.com"
          git config --global user.name "Gabriela Poncet"
          git add .
          git commit -m "Update deployment to latest image"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
