name: CI/CD Pipeline - Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Unit Tests
        run: ./gradlew test jacocoTestReport

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/

      - name: Check Quality Gate
        run: ./gradlew check
        continue-on-error: true

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gabiponcet/lanchonete-app:staging .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push gabiponcet/lanchonete-app:staging

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Start Minikube
        run: |
          minikube start --driver=docker --force
          sudo chown -R $USER $HOME/.kube $HOME/.minikube
          sudo chgrp -R $USER $HOME/.kube $HOME/.minikube
          export KUBECONFIG=$HOME/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Staging
        run: |
          for file in $(find k8s -name '*.yaml'); do
            kubectl apply -f $file --validate=false
          done
          kubectl rollout status deployment lanchonete-app-staging

      - name: Rollback Deployment
        if: failure()
        run: |
          kubectl rollout undo deployment lanchonete-app-staging
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Send Discord Failure Notification
        if: failure()
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"content":"⚠️ O deploy de staging falhou! A infra foi revertida. Verifique os logs para mais detalhes."}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Success Notification
        if: success()
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"content":"✅ O deploy de staging foi concluído com sucesso!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gabiponcet/lanchonete-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push gabiponcet/lanchonete-app:latest

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Start Minikube
        run: |
          minikube start --driver=docker --force
          sudo chown -R $USER $HOME/.kube $HOME/.minikube
          sudo chgrp -R $USER $HOME/.kube $HOME/.minikube
          export KUBECONFIG=$HOME/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Production
        run: |
          for file in $(find k8s -name '*.yaml'); do
            kubectl apply -f $file --validate=false
          done
          kubectl rollout status deployment lanchonete-app-production

      - name: Rollback Deployment
        if: failure()
        run: |
          kubectl rollout undo deployment lanchonete-app-production
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Send Discord Failure Notification
        if: failure()
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"content":"⚠️ O deploy de produção falhou! A infra foi revertida. Verifique os logs para mais detalhes."}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Success Notification
        if: success()
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"content":"✅ O deploy de produção foi concluído com sucesso!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}