name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Build Docker image
        run: docker build -t gabiponcet/lanchonete-app:latest .

      - name: Push Docker image
        run: docker push gabiponcet/lanchonete-app:latest

      - name: Clone Kubernetes repo
        run: git clone https://github.com/DenisWm/infra-k8s.git
        working-directory: k8s

      - name: Update Kubernetes manifests
        run: |
          find . -name 'deployment.yaml' -exec sed -i 's|image:.*|image: gabiponcet/lanchonete-app:latest|' {} +
        working-directory: k8s/infra-k8s

      - name: Commit and push changes to Kubernetes repo
        run: |
          cd k8s/infra-k8s
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Update deployment to latest image"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
